### ISSUE TITLE
1.18.2 mixin error

### ISSUE THREAD

**Issue by SettingDust** [ThinkingStudios/ContingameIME#2]
```
[20:49:07] [modloading-worker-0/WARN] (mixin) Mixin apply failed ingameime.forge.mixin.json:MixinBookEditScreen -> net.minecraft.client.gui.screens.inventory.BookEditScreen: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on ingameime.forge.mixin.json:MixinBookEditScreen->@Inject::onCaret_Book(Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lnet/minecraft/client/gui/screens/inventory/BookEditScreen$Pos2i;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [ -> Inject -> ingameime.forge.mixin.json:MixinBookEditScreen->@Inject::onCaret_Book(Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on ingameime.forge.mixin.json:MixinBookEditScreen->@Inject::onCaret_Book(Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lnet/minecraft/client/gui/screens/inventory/BookEditScreen$Pos2i;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [ -> Inject -> ingameime.forge.mixin.json:MixinBookEditScreen->@Inject::onCaret_Book(Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:517)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1355)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/imblocker@3.1.1/io.github.reserveword.imblocker.Config$Client.<init>(Config.java:57)
	at TRANSFORMER/forge@40.2.1/net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:615)
	at TRANSFORMER/imblocker@3.1.1/io.github.reserveword.imblocker.Config.<clinit>(Config.java:178)
	at TRANSFORMER/imblocker@3.1.1/io.github.reserveword.imblocker.IMBlocker.<init>(IMBlocker.java:24)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.2.1/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.1/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

[20:49:07] [modloading-worker-0/WARN] (mixin) Injection warning: LVT in net/minecraft/client/gui/screens/inventory/SignEditScreen::m_6305_(Lcom/mojang/blaze3d/vertex/PoseStack;IIF)V has incompatible changes at opcode 358 in callback ingameime.forge.mixin.json:MixinEditSignScreen->@Inject::onCaret_Sign(Lcom/mojang/blaze3d/vertex/PoseStack;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;FLnet/minecraft/world/level/block/state/BlockState;ZZFLnet/minecraft/client/renderer/MultiBufferSource$BufferSource;FIIIILcom/mojang/math/Matrix4f;ILjava/lang/String;FII)V.
 Expected: [F, Lnet/minecraft/world/level/block/state/BlockState;, Z, Z, F, Lnet/minecraft/client/renderer/MultiBufferSource$BufferSource;, F, I, I, I, I, Lcom/mojang/math/Matrix4f;, I, Ljava/lang/String;, F, I, I]
    Found: [F, Lnet/minecraft/world/level/block/state/BlockState;, Z, Z, F, Lnet/minecraft/client/renderer/MultiBufferSource$BufferSource;, Lnet/minecraft/client/resources/model/Material;, Lcom/mojang/blaze3d/vertex/VertexConsumer;, F, I, I, I, I, Lcom/mojang/math/Matrix4f;, I, Ljava/lang/String;, F]
Available: [F, Lnet/minecraft/world/level/block/state/BlockState;, Z, Z, F, Lnet/minecraft/client/renderer/MultiBufferSource$BufferSource;, Lnet/minecraft/client/resources/model/Material;, Lcom/mojang/blaze3d/vertex/VertexConsumer;, F, I, I, I, I, Lcom/mojang/math/Matrix4f;, I, Ljava/lang/String;, F, I, I]
[20:49:07] [modloading-worker-0/WARN] (mixin) Injection warning: LVT in net/minecraft/client/gui/screens/inventory/SignEditScreen::m_6305_(Lcom/mojang/blaze3d/vertex/PoseStack;IIF)V has incompatible changes at opcode 459 in callback ingameime.forge.mixin.json:MixinEditSignScreen->@Inject::onCaret_Sign(Lcom/mojang/blaze3d/vertex/PoseStack;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;FLnet/minecraft/world/level/block/state/BlockState;ZZFLnet/minecraft/client/renderer/MultiBufferSource$BufferSource;FIIIILcom/mojang/math/Matrix4f;ILjava/lang/String;FII)V.
 Expected: [F, Lnet/minecraft/world/level/block/state/BlockState;, Z, Z, F, Lnet/minecraft/client/renderer/MultiBufferSource$BufferSource;, F, I, I, I, I, Lcom/mojang/math/Matrix4f;, I, Ljava/lang/String;, F, I, I]
    Found: [F, Lnet/minecraft/world/level/block/state/BlockState;, Z, Z, F, Lnet/minecraft/client/renderer/MultiBufferSource$BufferSource;, Lnet/minecraft/client/resources/model/Material;, Lcom/mojang/blaze3d/vertex/VertexConsumer;, F, I, I, I, I, Lcom/mojang/math/Matrix4f;, I, Ljava/lang/String;, I]
Available: [F, Lnet/minecraft/world/level/block/state/BlockState;, Z, Z, F, Lnet/minecraft/client/renderer/MultiBufferSource$BufferSource;, Lnet/minecraft/client/resources/model/Material;, Lcom/mojang/blaze3d/vertex/VertexConsumer;, F, I, I, I, I, Lcom/mojang/math/Matrix4f;, I, Ljava/lang/String;, I, I, I]

```

**Comment by TexBlock** [comment]
fixed in 1.0.3 (1.18.x/1.19.2) & 1.0.1(1.17.x).
~~maybe?~~
